### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by IFedor-F** [camnwalter/Screenshots#2]
1. If minimize minecraft(press alt+tab) during the cropping, the game crash
2. If you want to cancel cropping and press esc, the cursor will not disappear

**Comment by camnwalter** [comment]
Thanks for the report! I'll see what I can do about the first one.  I did end up fixing the second one last night.

**Comment by camnwalter** [comment]
Fixed 1 in 5e6254f9f208a1b9ddd9258bc81bb19225675b22
Fixed 2 in c9f274bfe98ce235791d1d4ee7f765a7f0cdf9e7
