### ISSUE TITLE
Mouse click (drag) and hover events are passing through overlay

### ISSUE THREAD

**Issue by VidTu** [camnwalter/Screenshots#3]
How to reproduce both click and hover:
1. Use `/tellraw @s {"text":"example hovering and clicking text","clickEvent":{"action":"open_url","value":"https://example.com/"},"hoverEvent":{"action":"show_text","value":"pig pig pig pig"}}`
2. Open chat again.
3. Try to screenshot.
4. You can still click and hover on the text.
![image](https://github.com/camnwalter/Screenshots/assets/60929459/49450ca7-d9fc-4221-8cab-cc524577ecf7)

Also keyboard navigation events like tab and enter keys are passing to the underlying screen:

https://github.com/camnwalter/Screenshots/assets/60929459/da564ee2-ced3-4d75-b52e-ed1a68435eed

**Comment by camnwalter** [comment]
Thanks for the report!  I'll look into it!

**Comment by camnwalter** [comment]
Fixed in https://github.com/camnwalter/Screenshots/commit/67730599cd1692a4dc0713bc06696af1143faba8
